name: CI/CD Pipeline

# Trigger the workflow on pushes and pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use AdoptOpenJDK
          java-version: '11' # Specify your project's Java version

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # Step 4: Install Chromedriver
      - name: Install Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          export PATH=$PATH:/usr/lib/chromium-browser/
          echo "Chromedriver version:"
          chromedriver --version

      # Step 5: Build the project
      - name: Build with Maven
        run: mvn clean install

      # Step 6: Run tests
      - name: Run tests
        env:
          PATH: $PATH:/usr/lib/chromium-browser/ # Ensure Chromedriver is in PATH
        run: mvn test
